services:
  - type: web
    name: playwright-dashboard
    env: node
    buildCommand: |
      npm install
      npm run build
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npx playwright install chromium
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
    healthCheckPath: /
    autoDeploy: true 