services:
  - type: web
    name: playwright-ui-interface
    env: node
    plan: free
    branch: main  # change if needed
    buildCommand: |
      npm install
      npx playwright install
      npx playwright test --reporter=list
      npm run build
    startCommand: npm run start
    buildFilter:
      paths:
        - tests/**/*
        - playwright.config.ts
        - package.json
        - next.config.js
        - tsconfig.json
        - src/**/*
        - public/**/*
        - .env
    envVars:
      - key: NODE_ENV
        value: production
